build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:latest
  amd64: ghcr.io/home-assistant/amd64-base:latest
  armhf: ghcr.io/home-assistant/armhf-base:latest
  armv7: ghcr.io/home-assistant/armv7-base:latest
  i386: ghcr.io/home-assistant/i386-base:latest
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Synapse Matrix Server"
  org.opencontainers.image.description: "Matrix homeserver written in Python/Twisted + Rust"
  org.opencontainers.image.source: "https://github.com/MichalTorma/ha-synapse"
  org.opencontainers.image.licenses: "AGPL-3.0"
  org.opencontainers.image.documentation: "https://github.com/MichalTorma/ha-synapse/blob/main/README.md"
args:
  SYNAPSE_VERSION: "1.137.0"
